default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password  # thay đổi theo thông tin thực tế của bạn
  host: localhost

development:
  <<: *default
  host: db
  database: my_api_development

test:
  <<: *default
  database: my_api_test

production:
  <<: *default
  database: my_api_production
  username: my_api
  password: <%= ENV['MY_API_DATABASE_PASSWORD'] %>
